### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by luiscarrillo310** [Nuts-Bolts-FRC-7528/FRC-2020#3] opened 2020-01-16 00:14 UTC
One joystick with Arcade Drive, dead band of 5%, and a single print out for string builder, and some statistics surrounding the code.

**Comment by OccultSlolem** [comment] 2020-01-16 01:55
Closing this issue as it is a duplicate of #2

**Closed as completed by OccultSlolem** 2020-01-16 01:55 UTC
Labels: duplicate
